name: Build

on:
  push:
    branches:
      - main
    tags:
      - "*"
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

  NUGET_FEED: https://api.nuget.org/v3/index.json

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: "6.3.x"
      - name: GitVersion - Determine Version
        uses: gittools/actions/gitversion/execute@v3.2.1
        id: gitversion

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore
        run: dotnet restore --verbosity normal
      - name: Build
        run: dotnet build -c Release --no-restore --verbosity normal
      - name: Test
        run: dotnet test -c Release --no-restore --no-build --verbosity normal
      - name: Pack
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet pack -c Release --no-restore --no-build -v normal -p:Version='${{ steps.gitversion.outputs.NuGetVersion }}'
      - name: Push to NuGet
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet nuget push ./HyrumToken/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s ${{ env.NUGET_FEED }}
